# Generated by Django 2.0.7 on 2018-07-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['-price', 'name']},
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
